### ISSUE TITLE
getModelFit throwing error regarding dimnames

### ISSUE THREAD

**Issue by zdebruine** [zdebruine/singlet#22]
Line 19 in https://github.com/zdebruine/singlet/blob/main/R/getModelFit.R (`stopifnot(all(rownames(design) %in% colnames(dat)))`) is activating for most cases of `AnnotateNMF`.  Only the example seems to run smoothly for the most part.  

Looking for an easy reprex.

@ttriche

**Comment by ttriche** [comment]
can you provide such a reprex @zdebruine  ?  :-D

**Comment by zdebruine** [comment]
Not until 5:30 today.  Try almost any Seurat object.

**Comment by ttriche** [comment]
alright well, send me one when you have one.  I'm slammed today unless my class gets canceled

**Comment by ttriche** [comment]
oh ugh I bet I know what's going on here.  That check is important but it can probably be finessed
