### ISSUE TITLE
RunGSEA(pbmc3k,verbose = FALSE) gives empty results using example data

### ISSUE THREAD

**Issue by rosaranli** [zdebruine/singlet#26]
Thanks for this nice tool. Really helpful. I tried to go through the command lines in the https://zdebruine.github.io/singlet/articles/Guided_Clustering_with_NMF.html and everything went well except RunGSEA gives empty misc slots. There are no error messages. But when I ran GSEAHeatmap function the error message is like
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
In addition: Warning message:
In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL
which indicates it's a empty input. 

Has anyone seen this before or do you have an idea what could cause this?

Thank you very much!

**Comment by zdebruine** [comment]
Yes, known issue indeed.  I'll fix this later this summer, will leave this open until then.  You can use `fgsea` and/or `msigdbr` on individual NMF factors to achieve a very similar effect, however.

**Comment by earbebarnes** [comment]
I believe the error may be in not loading the Matrix package for the Diagonal() function, and in not having the row names in df2. I think I have fixed it by adding   rownames(df2) <- rownames(df) i.e. 
library(Matrix)
 GSEAHeatmap <- function(object, reduction = "nmf", max.terms.per.factor = 3, dropcommon = TRUE) {

  if (is(object, "Seurat")) {
    df <- object@reductions[[reduction]]@misc$gsea$padj
  } else if (is(object, "nmf")) {
    df <- object@misc$gsea$padj
  }

  # markers for each factor based on the proportion of signal in that factor
  df2 <- as.matrix(Diagonal(x = 1 / rowSums(df)) %*% df)
  rownames(df2) <- rownames(df) #add row names to df2

**Comment by zdebruine** [comment]
@earbebarnes You are awesome!  Thanks for taking the time to figure this out.  

I can confirm that the guided clustering vignette including `RunGSEA()` is now working!
