### ISSUE TITLE
Rlog1p error

### ISSUE THREAD

**Issue by jemorlanes** [zdebruine/singlet#27]
Hi!

I am running into an issue when trying to install singlet. I know you guys have mentioned that the release is not stable yet, but I am posting this issue here just in case it might be informative down the line :)

Here is the installation command I'm running as well as the traceback:
`> devtools::install_github("zdebruine/singlet")
Downloading GitHub repo zdebruine/singlet@HEAD
Skipping 2 packages not available: fgsea, limma
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/z8/nrcst881607gn95xh3_4qvb00000gp/T/RtmpdgJoYl/remotesb5ead0e980/zdebruine-singlet-e3f67ce/DESCRIPTION’ (416ms)
─  preparing ‘singlet’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘singlet/data/pbmc3k.RData’
─  building ‘singlet_0.99.20220222.1.tar.gz’
   
* installing *source* package ‘singlet’ ...
** using staged installation
** libs
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -I"/Users/javierescudero/miniconda3/envs/R423/lib/R/include" -DNDEBUG -I../inst/include/ -I'/Users/javierescudero/miniconda3/envs/R423/lib/R/library/Rcpp/include' -D_FORTIFY_SOURCE=2 -isystem /Users/javierescudero/miniconda3/envs/R423/include -mmacosx-version-min=11.0 -I/Users/javierescudero/miniconda3/envs/R423/include  -fopenmp -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/javierescudero/miniconda3/envs/R423/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1678912368421/work=/usr/local/src/conda/r-base-4.2.3 -fdebug-prefix-map=/Users/javierescudero/miniconda3/envs/R423=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -I"/Users/javierescudero/miniconda3/envs/R423/lib/R/include" -DNDEBUG -I../inst/include/ -I'/Users/javierescudero/miniconda3/envs/R423/lib/R/library/Rcpp/include' -D_FORTIFY_SOURCE=2 -isystem /Users/javierescudero/miniconda3/envs/R423/include -mmacosx-version-min=11.0 -I/Users/javierescudero/miniconda3/envs/R423/include  -fopenmp -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/javierescudero/miniconda3/envs/R423/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1678912368421/work=/usr/local/src/conda/r-base-4.2.3 -fdebug-prefix-map=/Users/javierescudero/miniconda3/envs/R423=/usr/local/src/conda-prefix  -c singlet.cpp -o singlet.o
singlet.cpp:1:9: warning: 'EIGEN_NO_DEBUG' macro redefined [-Wmacro-redefined]
#define EIGEN_NO_DEBUG
        ^
<command line>:4:9: note: previous definition is here
#define EIGEN_NO_DEBUG 1
        ^
singlet.cpp:2:9: warning: 'EIGEN_INITIALIZE_MATRICES_BY_ZERO' macro redefined [-Wmacro-redefined]
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO
        ^
<command line>:3:9: note: previous definition is here
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO 1
        ^
singlet.cpp:33:5: warning: non-void function does not return a value [-Wreturn-type]
    }
    ^
singlet.cpp:876:26: error: no member named 'Rlog1p' in namespace 'std'; did you mean simply 'Rlog1p'?
            it.value() = std::log1p(it.value() * norm);
                         ^~~~~~~~~~
                         Rlog1p
/Users/javierescudero/miniconda3/envs/R423/lib/R/include/Rmath.h:72:9: note: 'Rlog1p' declared here
double  Rlog1p(double);
        ^
3 warnings and 1 error generated.
make: *** [/Users/javierescudero/miniconda3/envs/R423/lib/R/etc/Makeconf:178: singlet.o] Error 1
ERROR: compilation failed for package ‘singlet’
* removing ‘/Users/javierescudero/miniconda3/envs/R423/lib/R/library/singlet’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/z8/nrcst881607gn95xh3_4qvb00000gp/T//RtmpdgJoYl/fileb5ea1391d2eb/singlet_0.99.20220222.1.tar.gz’ had non-zero exit status
> 
> devtools::install_github("zdebruine/singlet")
Downloading GitHub repo zdebruine/singlet@HEAD
Skipping 2 packages not available: fgsea, limma
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/z8/nrcst881607gn95xh3_4qvb00000gp/T/RtmpdgJoYl/remotesb5ea56840aaa/zdebruine-singlet-e3f67ce/DESCRIPTION’ (430ms)
─  preparing ‘singlet’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘singlet/data/pbmc3k.RData’
─  building ‘singlet_0.99.20220222.1.tar.gz’
   
* installing *source* package ‘singlet’ ...
** using staged installation
** libs
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -I"/Users/javierescudero/miniconda3/envs/R423/lib/R/include" -DNDEBUG -I../inst/include/ -I'/Users/javierescudero/miniconda3/envs/R423/lib/R/library/Rcpp/include' -D_FORTIFY_SOURCE=2 -isystem /Users/javierescudero/miniconda3/envs/R423/include -mmacosx-version-min=11.0 -I/Users/javierescudero/miniconda3/envs/R423/include  -fopenmp -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/javierescudero/miniconda3/envs/R423/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1678912368421/work=/usr/local/src/conda/r-base-4.2.3 -fdebug-prefix-map=/Users/javierescudero/miniconda3/envs/R423=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -I"/Users/javierescudero/miniconda3/envs/R423/lib/R/include" -DNDEBUG -I../inst/include/ -I'/Users/javierescudero/miniconda3/envs/R423/lib/R/library/Rcpp/include' -D_FORTIFY_SOURCE=2 -isystem /Users/javierescudero/miniconda3/envs/R423/include -mmacosx-version-min=11.0 -I/Users/javierescudero/miniconda3/envs/R423/include  -fopenmp -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/javierescudero/miniconda3/envs/R423/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1678912368421/work=/usr/local/src/conda/r-base-4.2.3 -fdebug-prefix-map=/Users/javierescudero/miniconda3/envs/R423=/usr/local/src/conda-prefix  -c singlet.cpp -o singlet.o
singlet.cpp:1:9: warning: 'EIGEN_NO_DEBUG' macro redefined [-Wmacro-redefined]
#define EIGEN_NO_DEBUG
        ^
<command line>:4:9: note: previous definition is here
#define EIGEN_NO_DEBUG 1
        ^
singlet.cpp:2:9: warning: 'EIGEN_INITIALIZE_MATRICES_BY_ZERO' macro redefined [-Wmacro-redefined]
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO
        ^
<command line>:3:9: note: previous definition is here
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO 1
        ^
singlet.cpp:33:5: warning: non-void function does not return a value [-Wreturn-type]
    }
    ^
singlet.cpp:876:26: error: no member named 'Rlog1p' in namespace 'std'; did you mean simply 'Rlog1p'?
            it.value() = std::log1p(it.value() * norm);
                         ^~~~~~~~~~
                         Rlog1p
/Users/javierescudero/miniconda3/envs/R423/lib/R/include/Rmath.h:72:9: note: 'Rlog1p' declared here
double  Rlog1p(double);
        ^
3 warnings and 1 error generated.
make: *** [/Users/javierescudero/miniconda3/envs/R423/lib/R/etc/Makeconf:178: singlet.o] Error 1
ERROR: compilation failed for package ‘singlet’
* removing ‘/Users/javierescudero/miniconda3/envs/R423/lib/R/library/singlet’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/z8/nrcst881607gn95xh3_4qvb00000gp/T//RtmpdgJoYl/fileb5ea76d84b45/singlet_0.99.20220222.1.tar.gz’ had non-zero exit status`

My system is MacOS Ventura 13.3 with a M1 Pro (arm64) chip. I have tried some potential solutions to this issue as discussed here (https://github.com/satijalab/sctransform/issues/135), but it doesn't work for me:

`> Sys.getenv("PKG_CPPFLAGS")
[1] "-DHAVE_WORKING_LOG1P"`

Thank you for your time!!

**Comment by zdebruine** [comment]
Interesting, thanks for raising this issue.  Since the use of `std::log1p` is not mission-critical, I removed my implementation and instead now call `Seurat::LogNormalize`.  Does it work for you now?

**Comment by jemorlanes** [comment]
Thanks for the fast reply!

Now it seems to be fixed. It raises the same variables as warnings, but the compilation doesn't stop there. Now I am getting an issue with RcppML, but I am looking now if the issue comes from my environment!

`> devtools::install_github("zdebruine/singlet")
Downloading GitHub repo zdebruine/singlet@HEAD
Skipping 2 packages not available: fgsea, limma
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/z8/nrcst881607gn95xh3_4qvb00000gp/T/RtmpFNX6Hk/remotes1558f15a57a2f/zdebruine-singlet-750e55e/DESCRIPTION’ (389ms)
─  preparing ‘singlet’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘singlet/data/pbmc3k.RData’
─  building ‘singlet_0.99.21.tar.gz’
   
* installing *source* package ‘singlet’ ...
** using staged installation
** libs
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -I"/Users/javierescudero/miniconda3/envs/R423/lib/R/include" -DNDEBUG -I../inst/include/ -I'/Users/javierescudero/miniconda3/envs/R423/lib/R/library/Rcpp/include' -D_FORTIFY_SOURCE=2 -isystem /Users/javierescudero/miniconda3/envs/R423/include -mmacosx-version-min=11.0 -I/Users/javierescudero/miniconda3/envs/R423/include  -fopenmp -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/javierescudero/miniconda3/envs/R423/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1678912368421/work=/usr/local/src/conda/r-base-4.2.3 -fdebug-prefix-map=/Users/javierescudero/miniconda3/envs/R423=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -I"/Users/javierescudero/miniconda3/envs/R423/lib/R/include" -DNDEBUG -I../inst/include/ -I'/Users/javierescudero/miniconda3/envs/R423/lib/R/library/Rcpp/include' -D_FORTIFY_SOURCE=2 -isystem /Users/javierescudero/miniconda3/envs/R423/include -mmacosx-version-min=11.0 -I/Users/javierescudero/miniconda3/envs/R423/include  -fopenmp -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/javierescudero/miniconda3/envs/R423/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/r-base-split_1678912368421/work=/usr/local/src/conda/r-base-4.2.3 -fdebug-prefix-map=/Users/javierescudero/miniconda3/envs/R423=/usr/local/src/conda-prefix  -c singlet.cpp -o singlet.o
singlet.cpp:1:9: warning: 'EIGEN_NO_DEBUG' macro redefined [-Wmacro-redefined]
#define EIGEN_NO_DEBUG
        ^
<command line>:4:9: note: previous definition is here
#define EIGEN_NO_DEBUG 1
        ^
singlet.cpp:2:9: warning: 'EIGEN_INITIALIZE_MATRICES_BY_ZERO' macro redefined [-Wmacro-redefined]
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO
        ^
<command line>:3:9: note: previous definition is here
#define EIGEN_INITIALIZE_MATRICES_BY_ZERO 1
        ^
singlet.cpp:33:5: warning: non-void function does not return a value [-Wreturn-type]
    }
    ^
3 warnings generated.
arm64-apple-darwin20.0.0-clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Users/javierescudero/miniconda3/envs/R423/lib/R/lib -Wl,-dead_strip_dylibs -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/javierescudero/miniconda3/envs/R423/lib -L/Users/javierescudero/miniconda3/envs/R423/lib -o singlet.dylib RcppExports.o singlet.o -fopenmp -L/Users/javierescudero/miniconda3/envs/R423/lib/R/lib -lRlapack -L/Users/javierescudero/miniconda3/envs/R423/lib/R/lib -lRblas -L/Users/javierescudero/miniconda3/envs/R423/lib/gcc/arm64-apple-darwin20.0.0/11.3.0 -lgfortran -lm -L/Users/javierescudero/miniconda3/envs/R423/lib/R/lib -lR -Wl,-framework -Wl,CoreFoundation
ld: warning: -pie being ignored. It is only used when linking a main executable
installing to /Users/javierescudero/miniconda3/envs/R423/lib/R/library/00LOCK-singlet/00new/singlet/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: class "nmf" is not exported by 'namespace:RcppML'
Execution halted
ERROR: lazy loading failed for package ‘singlet’
* removing ‘/Users/javierescudero/miniconda3/envs/R423/lib/R/library/singlet’`

**Comment by zdebruine** [comment]
Sure, for now just run `devtools::install_github("zdebruine/RcppML")`, `BiocManager::install("fgsea")`, and `BiocManager::install("limma")` to get the necessary dependencies.  I'll try to cut some of these dependencies in the future to make life easier.

**Comment by jemorlanes** [comment]
I have installed RcppML succesfully, but the "nmf" class still raises an issue when loading singlet. So it appears as it has been installed succesfully, but there is a problem in the loading:
`> library(RcppML)
> library(singlet)
Error: package or namespace load failed for ‘singlet’:
 class "nmf" is not exported by 'namespace:RcppML'
> 
`

**Comment by jemorlanes** [comment]
Okay I managed to solve it! The installation went smoothly, thanks for your help!! :))

**Comment by zdebruine** [comment]
Great, could be smoother.  We have work to do!  Thanks.

**Comment by Ithinky** [comment]
@jemorlanes 
Hi,
jemorlanes

I have the same  question with you. When I download the singlet package, I encounter an error like this:
**Error: class "nmf" is not exported by 'namespace:RcppML'
Execution halted
ERROR: lazy loading failed for package ‘singlet’**

Could you give me some help? Thank you!

Best,
Ithinky

**Comment by Ithinky** [comment]
#25 OK I find the solution, sorry to bother you. @jemorlanes
