### ISSUE TITLE
RunGSEA getting stuck at 8%

### ISSUE THREAD

**Issue by Prathyusha-konda** [zdebruine/singlet#35]
Hi, Thanks for developing this tool. I've successfully used this to analyze some data but the RunGSEA command has been getting stuck at 8% for the last few days. I am unable to fix this/ move past this stage and was wondering if you know what might be the problem and how to fix this.

This error is unfortunately not reproducible with example pbmc3k data.

Thank you!

tumor<- NormalizeData(tumor, verbose = FALSE)
set.seed(123) 
tumor <- RunNMF(tumor, k=13)

tumor <- RunGSEA(tumor, category = "H", verbose = FALSE)
running GSEA on 13 factors...
  |============                                                                                                                                          |   8%

**Comment by zdebruine** [comment]
@Prathyusha-konda sorry for not trying to reproduce this.  Did you resolve your issue?  If so, what was the problem?

**Comment by Prathyusha-konda** [comment]
> @Prathyusha-konda sorry for not trying to reproduce this. Did you resolve your issue? If so, what was the problem?

Hi @zdebruine , unfortunately, I couldn't quite figure out why this happened as this was very specific to my nmf object. But I modified the seed and repeated the analysis and it's been fine. Do you have any thoughts on why this might have happened? Thanks!

**Comment by zdebruine** [comment]
I don't have any thoughts on why that happened.  I'm not able to reproduce, and so if you do get a seed that can reproduce feel free to reopen.  Otherwise, glad you got it sorted!
