### ISSUE TITLE
Issue with RunNMF on SeuratV5 objects

### ISSUE THREAD

**Issue by jemorlanes** [zdebruine/singlet#39]
Hey guys!!

Amazing package :). I have a quick comment regarding running the RunNMF() function on SeuratV5 objects. In these objects, the count data is stored in a `Assay5` class that doesn't have a `data` slot, which is what `RunNMF()` looks for right?

When I try to run it, I get the following error:
`> se <- RunNMF(se)
Error in RunNMF.Seurat(se) : 
  no slot of name "data" for this object of class "Assay5"`

If I explore my seurat object:
`> se[["Spatial"]]
Assay (v5) data with 37082 features for 174243 cells
First 10 features:
 MIR1302-2HG, FAM138A, OR4F5, AL627309.1, AL627309.3, AL627309.2,
AL627309.5, AL627309.4, AP006222.2, AL732372.1 
Layers:
 counts, data`

Then if I specify the assay, same error:
`> se <- RunNMF(se, assay = "data")
Error in object@assays[[assay]]@data : 
  no applicable method for `@` applied to an object of class "NULL"`

I have noted here [()](https://satijalab.org/seurat/articles/seurat5_essential_commands) that the assays in SeuratV5 are accessed with `$` instead of with `@`, so I think that if In the `RunNMF` function you change the accessing symbol, everything should be okay.
`> se@assays[["Spatial"]]@data
Error: no slot of name "data" for this object of class "Assay5"
> se@assays[["Spatial"]]$data[1:2,1:2]
2 x 2 sparse Matrix of class "dgCMatrix"
            spot1 spot2
MIR1302-2HG                     .                     .
FAM138A                         .                     .`

**Comment by jemorlanes** [comment]
I have managed to make it work by creating a S3 assay inside my S5 object. However, now I am running into a different error:
`REPLICATE  1 / 2                                                                                                                                                                           
k = 2 , rep = 1                                                                                                                                                                            
   test_error = 1.6387e-01                                                                                                                                                                 
   not overfit                                                                                                                                                                             
   best rank in replicate = 2                                                                                                                                                              
                                                                                                                                                                                           
k = 3 , rep = 1                                                                                                                                                                            
   test_error = 1.6254e-01                                                                                                                                                                 
   overfit (overfit_score = 1.4863e-03 )                                                                                                                                                   
   best rank in replicate = 2                                                                                                                                                              
                                                                                                                                                                                           
k = 1 , rep = 1                                                                                                                                                                            
Error in `map()`:                                                                                                                                                                          
ℹ In index: 1.                                                                                                                                                                             
ℹ With name: 16um.                                                                                                                                                                         
Caused by error:                                                                                                                                                                           
! Not a matrix.  `

More of the backtrace:
`  9. │     ├─singlet::RunNMF(se_sub, assay = "Spatial3", reps = 2)
 10. │     └─singlet:::RunNMF.Seurat(se_sub, assay = "Spatial3", reps = 2)
 11. │       └─singlet::ard_nmf(...)
 12. │         └─singlet:::c_ard_nmf(...)`

**Comment by zdebruine** [comment]
@jemorlanes Thanks for creating this issue.  Do you mind submitting a pull request with your fix that supports Seurat v5 objects when a dgCMatrix is used internally?  However, we will need to throw an error if a custom data structure is used in the v5 object (i.e. BPCells) since we cannot support those with our existing backend.

The issue you encountered at `k = 1` is different -- that is a known bug that we need to fix (https://github.com/zdebruine/singlet/issues/31).  A matrix with a rank of 1 is being collapsed to a vector in R that is causing an issue being coerced to Eigen::MatrixXd in the Rcpp wrapper.

**Comment by jemorlanes** [comment]
I did  not make any changes in the `RunNMF` function, I just used a function from SeuratV5 that allows you to create, inside your V5 object, an assay that is V4 or V3. Then I specified that assay in `RunNMF`, and the function managed to run. The following is the snipped I used for running NMF on my object, which is a tad ugly:

`
  se_sub <- se_obj[VariableFeatures(se_obj), ]

  % NOTES FROM 240108. In SeuratV5, which is the one loaded here, they changed how the assays are
  %% accessed. Now we have to use "$" instead of "@". RunNMF must accesses it with "@", so it doesnt work
  %% with the updated Seurat version. Therefore, I am going to create a new assay in the V5 seurat that 
  %% is the same as the one that RunNMF is expecting, so V3

  se_sub[["Spatial3"]] <- as(object = se_sub[["Spatial"]], Class = "Assay")

  % Set seed for reproducibility

  set.seed(9)
  se_sub <- RunNMF(se_sub, assay = "Spatial3", reps = 2)
`

I do not know how `RunNMF` retrieves the data from the `data` layer, but I imagine it's with the "@" operator, which is for previous Seurat versions. In my code I just wrapped around this issue by creating a SeuratV3 assay inside my V5 object, but if you add a check in `RunNMF` where, if the class of the assay is `Assay5` or something like that, the `data` layer is retrieved by `se@assays[["Spatial"]]$data` (V5) instead of by `se@assays[["Spatial"]]@data` (V3).

So, in my assay "Spatial3", you access the normalized count data with `se@assays[["Spatial3"]]@data`, which is what I assume `RunNMF` does internally :)
This is just an assumption of how I guess `RunNMF` is retrieving the count data, I'm not sure if this is exactly how the function does it :)

Regarding the issue with `k = 1`, thanks for letting me know you guys are looking into it! I will add a comment in the corresponding thread

**Comment by zdebruine** [comment]
Got it.  I'll try to get to this in a bit.  We also have a ton of other changes in the queue as well, particularly on a new data structure, which will largely replace the need for using any Seurat v5 data structure at all -- far more compressed and just as fast to compute over.

**Comment by jemorlanes** [comment]
Awesome! Looking forward to that :)

I have encountered a new issue. Since it is the first time that it appears to me and I do not know if it could be cause to potential incompatibilities with SeuratV5, I'm going to mention it here. Let me know if I should open a new issue or here is okay.

So when specifying the `assay = "Spatial3"` I manage to start the function. But at the end, once the optimal rank has been identified, I get a new error message:
`
se_sub <- RunNMF(se_sub, assay = "Spatial3", threads = 0)
running with sparse optimization

REPLICATE  1 / 3 
k = 2 , rep = 1 
   test_error = 7.5808e-02 
   possibly overfit (overfit_score = 4.3199e-06 )
   best rank in replicate = 2 

k = 3 , rep = 1 
   test_error = 7.5517e-02 
   possibly overfit (overfit_score = 7.6131e-06 )
   best rank in replicate = 3 

k = 6 , rep = 1 
   test_error = 7.5291e-02 
   overfit (overfit_score = 1.2713e-04 )
   best rank in replicate = 3 

k = 4 , rep = 1 
   test_error = 7.5356e-02 
   possibly overfit (overfit_score = 9.9452e-06 )
   best rank in replicate = 4 

k = 5 , rep = 1 
   test_error = 7.5348e-02 
   possibly overfit (overfit_score = 7.6379e-05 )
   best rank in replicate = 5 


REPLICATE  2 / 3 
k = 2 , rep = 2 
   test_error = 7.5745e-02 
   not overfit
   best rank in replicate = 2 

k = 3 , rep = 2 
   test_error = 7.5453e-02 
   possibly overfit (overfit_score = 8.0154e-06 )
   best rank in replicate = 3 


REPLICATE  3 / 3 
k = 2 , rep = 3 
   test_error = 7.5816e-02 
   possibly overfit (overfit_score = 8.1400e-06 )
   best rank in replicate = 2 

k = 3 , rep = 3 
   test_error = 7.5523e-02 
   possibly overfit (overfit_score = 2.4428e-05 )
   best rank in replicate = 3 


Unmasking test set
Fitting final model at k = 3 
Error in c_nmf(A, At, tol, maxit, verbose > 2, L1, L2, threads, w_init_this) : 
  argument "threads" is missing, with no default
`

**Comment by zdebruine** [comment]
Aha, I reverted https://github.com/zdebruine/singlet/pull/40.  Does it work if you reinstall now?

**Comment by jemorlanes** [comment]
I reinstalled `(singlet_0.99.38)`, but I keep getting the same issue

**Comment by jemorlanes** [comment]
I've tried `RunNMF()` with older datasets and the same issue pops up, so it doesn't seem like it depends on the Seurat version:

`Unmasking test set
Fitting final model at k = 22 
Error in c_nmf(A, At, tol, maxit, verbose > 2, L1, L2, threads, w_init_this) : 
  argument "threads" is missing, with no default`

**Comment by MeiShuhao-Huashan** [comment]
I have the same issue, Error in c_nmf(A, At, tol, maxit, verbose > 2, L1, L2, threads, w_init_this) : 
  argument "threads" is missing, with no default
Called from: c_nmf(A, At, tol, maxit, verbose > 2, L1, L2, threads, w_init_this)

I reinstalled (singlet_0.99.38), but I keep getting the same issue as well.

**Comment by barunlz** [comment]
Hi Zach,
I am facing the same problem with singlet_0.99.38.
Error in c_nmf(A, At, tol, maxit, verbose > 2, L1, L2, threads, w_init_this) : argument "threads" is missing, with no default

**Comment by jemorlanes** [comment]
Hi! I managed to "solve" the issue by installing from previous commit for version `0.99.38`, here it is:
`devtools::install_github("zdebruine/singlet", ref="8ab019d")`

**Comment by zdebruine** [comment]
Threads issue resolved with https://github.com/zdebruine/singlet/commit/c98b871cf5540693be49e37bebc80416ff266a37.  Sorry for the delay, thank you for your patience!  Happy to answer any other unresolved questions related to this issue trail here, but will close for now.
