### ISSUE TITLE
split.by option in RunNMF

### ISSUE THREAD

**Issue by IsaacDiaz026** [zdebruine/singlet#42]
Hello,

I was wondering if you could explain what  the split.by function accomplished in the RunNMF function? Is it for including latent factors that you want to account for?

**Comment by zdebruine** [comment]
@IsaacDiaz026 Thanks for asking, I'll have to add more docs on this.  `split.by` is a factor of length `n` where `n` is the number of columns in your input matrix (i.e. each cell) giving metadata groups that should be considered equally in the NMF objective.  Basically, if I have a large control and small treatment group, splitting by the factor indicating group would allow the treatment to be just as important as the control group.

In practice, this is simply achieved by multiplying each group by a scalar such that each group sums to the same value.
