### ISSUE TITLE
Importing RcppML in NAMESPACE but not DESCRIPTION

### ISSUE THREAD

**Issue by zdebruine** [zdebruine/singlet#8]
Why is RcppML being loaded, technically we should move most C++ headers to RcppML in time, but at the moment RcppML is listed in the NAMESPACE but not in the DESCRIPTION as an imports.  Not clear what function is using this package.

**Comment by ttriche** [comment]
the nmf class is defined in RcppML IIRC

**Comment by zdebruine** [comment]
`devtools::check(vignettes = FALSE)` now passes with `0 errors ✔ | 0 warnings ✔ | 5 notes ✖`.  Examples are wrapped in `\dontrun{}` for sake of build time.  Examples will be unwrapped and a full `R CMD check --as-cran` run after all S4 methods are properly and exhaustively implemented.
